{
    "name": "Chaitanya Booking Flow",
    "summary": "Therapist availability selection before Odoo eCommerce checkout",
    "version": "18.0.2.0.0",
    "category": "Website/Website",
    "author": "Chaitanya",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "portal",
        "sale",
        "sale_management",
        "website",
        "website_sale",
    ],
    
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "views/service_category_views.xml",
        "views/service_views.xml",
        "views/provider_views.xml",
        "views/working_day_views.xml",
        "views/booking_views.xml",
        "views/voucher_views.xml",
        "views/compatibility_views.xml",
        "views/menu_views.xml",
        "views/website_templates.xml",
        "reports/booking_receipt_report.xml",
    ],
    "application": True,
    "installable": True,
}
