{
    "name": "Chaitanya Booking Flow",
    "summary": "Therapist availability selection before Odoo eCommerce checkout",
    "version": "18.0.2.0.0",
    "category": "Website/Website",
    "author": "Chaitanya",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "portal",
        "sale",
        "sale_management",
        "website",
        "website_sale",
        "account",
    ],
    
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        # "views/website_menu.xml",
        "data/sequence.xml",
        "views/service_category_views.xml",
        "views/attribute.xml",
        "views/service_views.xml",
        "views/provider_views.xml",
        "views/working_day_views.xml",
        "views/booking_views.xml",
        "views/voucher_views.xml",
        # "views/compatibility_views.xml",
        "views/menu_views.xml",
        "views/website_templates.xml",
        "views/cart_view.xml",
        "views/website_sale_inherit.xml",
        # "views/booking_cancel.xml",
        "reports/booking_receipt_report.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "chaitanya_booking_flow/static/src/js/checkout_card_slot_check.js",
            "chaitanya_booking_flow/static/src/js/variant_select.js",
            "chaitanya_booking_flow/static/src/css/delete_icon.css",    
        ],
    },
    "application": True,
    "installable": True,
}
